- name: Validate pre playbook
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: "{{ lookup('ansible.builtin.env', 'region') }}"
    ibmcloud_api_key: "{{ lookup('ansible.builtin.env', 'ibmcloud_api_key') }}"
    pi_networks: "{{ lookup('ansible.builtin.env', 'pi_networks') }}"
    pi_ssh_public_key_name: "{{ lookup('ansible.builtin.env', 'pi_ssh_public_key_name') }}"
    pi_existing_workspace_guid: "{{ lookup('ansible.builtin.env', 'pi_existing_workspace_guid') }}"
    ibmcloud_cos_service_credentials: "{{ lookup('ansible.builtin.env', 'ibmcloud_cos_service_credentials') | from_json }}"
    ibmcloud_cos_configuration: "{{ lookup('ansible.builtin.env', 'ibmcloud_cos_configuration') }}"
    ibmcloud_cos_endpoint_url_prod: "https://s3.dal.us.cloud-object-storage.appdomain.cloud"
    pi_oravg_volume: "{{ lookup('ansible.builtin.env', 'pi_oravg_volume') }}"
    pi_data_volume: "{{ lookup('ansible.builtin.env', 'pi_data_volume') }}"
    pi_redo_volume: "{{ lookup('ansible.builtin.env', 'pi_redo_volume') }}"
    pi_datavg_volume: "{{ lookup('ansible.builtin.env', 'pi_datavg_volume') }}"
    pi_volume_tier_list: ["tier0", "tier1", "tier3"]
  tasks:
    - name: Validate Count, Size and Tier attributes of pi_oravg_volume
      ansible.builtin.assert:
        that:
          - ((pi_oravg_volume | from_json).size | int) > 0
          - ((pi_oravg_volume | from_json).count | int) > 0
          - pi_volume_tier_list is ansible.builtin.contains((pi_oravg_volume | from_json).tier)
        fail_msg: "The 'pi_oravg_volume' - size and count must be numbers and tier should be one among {{ pi_volume_tier_list }}"
        success_msg: "Validation successful: 'pi_oravg_volume' - size and count are numbers and tier is one among {{ pi_volume_tier_list }}"
      when:
        - pi_oravg_volume | default('') | length > 0

    - name: Validate Count, Size and Tier attributes of pi_data_volume
      ansible.builtin.assert:
        that:
          - ((pi_data_volume | from_json).size | int) > 0
          - ((pi_data_volume | from_json).count | int) > 0
          - pi_volume_tier_list is ansible.builtin.contains((pi_data_volume | from_json).tier)
        fail_msg: "The 'pi_data_volume' - size and count must be numbers and tier should be one among {{ pi_volume_tier_list }}"
        success_msg: "Validation successful: 'pi_data_volume' - size and count are numbers and tier is one among {{ pi_volume_tier_list }}"
      when:
        - pi_data_volume | default('') | length > 0
    - name: Validate Count, Size and Tier attributes of pi_redo_volume
      ansible.builtin.assert:
        that:
          - ((pi_redo_volume | from_json).size | int) > 0
          - ((pi_redo_volume | from_json).count | int) > 0
          - pi_volume_tier_list is ansible.builtin.contains((pi_redo_volume | from_json).tier)
        fail_msg: "The 'pi_redo_volume' - size and count must be numbers and tier should be one among {{ pi_volume_tier_list }}"
        success_msg: "Validation successful: 'pi_redo_volume' - size and count are numbers and tier is one among {{ pi_volume_tier_list }}"
      when:
        - pi_redo_volume | default('') | length > 0

    - name: Validate Count, Size and Tier attributes of pi_datavg_volume
      ansible.builtin.assert:
        that:
          - ((pi_datavg_volume | from_json).size | int) > 0
          - ((pi_datavg_volume | from_json).count | int) > 0
          - pi_volume_tier_list is ansible.builtin.contains((pi_datavg_volume | from_json).tier)
        fail_msg: "The 'pi_datavg_volume' - size and count must be numbers and tier should be one among {{ pi_volume_tier_list }}"
        success_msg: "Validation successful: 'pi_datavg_volume' - size and count are numbers and tier is one among {{ pi_volume_tier_list }}"
      when:
        - pi_datavg_volume | default('') | length > 0


    - name: All IBM Cloud pre-validations passed
      ansible.builtin.debug:
        msg: "IBM Cloud all validations completed successfully."
