- name: Validate pre playbook
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: "{{ lookup('ansible.builtin.env', 'region') }}"
    ibmcloud_api_key: "{{ lookup('ansible.builtin.env', 'ibmcloud_api_key') }}"
    pi_networks: "{{ lookup('ansible.builtin.env', 'pi_networks') }}"
    pi_ssh_public_key_name: "{{ lookup('ansible.builtin.env', 'pi_ssh_public_key_name') }}"
    pi_existing_workspace_guid: "{{ lookup('ansible.builtin.env', 'pi_existing_workspace_guid') }}"
    ibmcloud_cos_service_credentials: "{{ lookup('ansible.builtin.env', 'ibmcloud_cos_service_credentials') }}"
    ibmcloud_cos_configuration: "{{ lookup('ansible.builtin.env', 'ibmcloud_cos_configuration') }}"
    ibmcloud_cos_endpoint_url_prod: "https://s3.dal.us.cloud-object-storage.appdomain.cloud"
    bastion_host_ip: "{{ lookup('ansible.builtin.env', 'bastion_host_ip') }}"
    ssh_private_key: "{{ lookup('ansible.builtin.env', 'ssh_private_key') }}"
  tasks:
    - name: Create a new IBM Cloud CLI session
      ansible.builtin.command:
        cmd: ibmcloud login --apikey {{ ibmcloud_api_key }} --no-region
      register: login_output
      changed_when: false
      failed_when: "'FAILED' in login_output.stderr"
      when:
        - ibmcloud_api_key | default('') | length > 0
        - region | default('') | length > 0

    - name: Debug login success
      ansible.builtin.debug:
        msg: "Successfully logged in IBM Cloud"

    - name: Capture the output of get workspace command
      ansible.builtin.command:
        cmd: ibmcloud pi ws get {{ pi_existing_workspace_guid }} --json
      register: get_ws_output
      changed_when: false
      failed_when: >
        'FAILED' in get_ws_output.stderr or
        ((get_ws_output.stdout | from_json).status | lower != 'active')
      when:
        - pi_existing_workspace_guid | default('') | length > 0

    - name: Extract the CRN of the given Workspace ID (JSON fetch)
      ansible.builtin.set_fact:
        workspace_crn: "{{ (get_ws_output.stdout | from_json).details.crn }}"
      when:
        - get_ws_output is defined
        - get_ws_output.stdout | default('') | length > 0
      changed_when: false

    - name: Setting the target workspace
      ansible.builtin.command:
        cmd: ibmcloud pi ws tg {{ workspace_crn }}
      register: target_ws_output
      changed_when: false
      failed_when: "'FAILED' in target_ws_output.stderr"
      when:
        - workspace_crn | default('') | length > 0

    - name: Validate the supplied Public SSH key
      ansible.builtin.command:
        cmd: ibmcloud pi ssh get {{ pi_ssh_public_key_name }} --json
      register: validate_ssh_output
      changed_when: false
      failed_when: "'FAILED' in validate_ssh_output.stderr"
      when:
        - pi_ssh_public_key_name | default('') | length > 0

    - name: Debug Public SSH key
      ansible.builtin.debug:
        msg: "The Public SSH key {{ pi_ssh_public_key_name }} is valid."

    - name: Connect to the COS Instance using the API key
      ansible.builtin.shell: >
        set -o pipefail &&
        ibmcloud login --no-region --apikey {{ (ibmcloud_cos_service_credentials | from_json).apikey }}
      register: cos_login_output
      changed_when: false
      failed_when: "'FAILED' in cos_login_output.stderr"
      when:
        - ibmcloud_cos_service_credentials | default('') | length > 0

    - name: Debug COS ibmcloud_cos_configuration
      ansible.builtin.debug:
        msg: "COS Configuration: {{ ibmcloud_cos_configuration }}"

    - name: Configure COS CRN
      ansible.builtin.command:
        cmd: ibmcloud cos config set crn {{ (ibmcloud_cos_service_credentials | from_json).resource_instance_id }}
      changed_when: false
      when:
        - ibmcloud_cos_service_credentials | default('') | length > 0

    - name: Configure endpoint-url
      ansible.builtin.command:
        cmd: ibmcloud cos config set endpoint-url "{{ ibmcloud_cos_endpoint_url_prod }}"
      changed_when: false
      when:
        - ibmcloud_cos_service_credentials | default('') | length > 0

    - name: Check if the supplied COS bucket exists
      ansible.builtin.shell: >
        set -o pipefail &&
        ibmcloud cos list-buckets | grep "{{ (ibmcloud_cos_configuration | from_json).cos_bucket_name }}"
      register: cos_bucket_list_check_output
      changed_when: false
      failed_when: cos_bucket_list_check_output.stdout == ""
      when:
        - (ibmcloud_cos_configuration | from_json).cos_bucket_name | default('') | length > 0

    - name: Create a new IBM Cloud CLI session
      ansible.builtin.command:
        cmd: ibmcloud login --apikey {{ ibmcloud_api_key }} --no-region
      register: login_output
      changed_when: false
      failed_when: "'FAILED' in login_output.stderr"
      when:
        - ibmcloud_api_key | default('') | length > 0
        - region | default('') | length > 0

    - name: Validate each subnet ID in workspace {{ pi_existing_workspace_guid }}
      ansible.builtin.shell: >
        set -o pipefail &&
        ibmcloud pi subnet get {{ item.id }} --json
      register: subnet_check
      changed_when: false
      failed_when: subnet_check.rc != 0
      loop: "{{ pi_networks }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Detect OS type
      ansible.builtin.command: uname
      register: os_type
      changed_when: false

    - name: Debug OS type
      ansible.builtin.debug:
        msg: "Operating System detected: {{ os_type.stdout }}"

    # Install ping based on OS if missing
    - name: Ensure ping is installed on Linux (RHEL/CentOS)
      ansible.builtin.package:
        name: iputils
        state: present
      register: iputils_install
      when:
        - os_type.stdout == "Linux"
      failed_when:
        - iputils_install.rc is defined
        - iputils_install.rc != 0

    - name: Detect ping path
      ansible.builtin.command: which ping
      register: ping_path
      changed_when: false
      ignore_errors: true

    - name: Debug ping path
      ansible.builtin.debug:
        msg: "Ping binary located at: {{ ping_path.stdout | default('Not found') }}"

    - name: Check if bastion host is reachable via ping
      ansible.builtin.command: "{{ ping_path.stdout }} -c 2 {{ bastion_host_ip }}"
      register: ping_result
      changed_when: false
      failed_when: ping_result.rc != 0
      when:
        - ping_path.stdout != ""
        - bastion_host_ip | default('') | length > 0

    - name: Validate SSH connectivity to bastion host using inline private key
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no \
            -i <(echo "{{ ssh_private_key }}") \
            root@{{ bastion_host_ip }} "exit"
      args:
        executable: /bin/bash
      register: ssh_result
      changed_when: false
      failed_when: ssh_result.rc != 0
      when:
        - ssh_private_key | default('') | length > 0
        - bastion_host_ip | default('') | length > 0

    - name: Debug Bastion Host connectivity
      ansible.builtin.debug:
        msg: "Successfully reached and authenticated to Bastion Host {{ bastion_host_ip }}"

    - name: All IBM Cloud pre-validations passed
      ansible.builtin.debug:
        msg: "IBM Cloud all validations completed successfully."
