- name: Validate pre playbook
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    region: "{{ lookup('ansible.builtin.env', 'region') }}"
    ibmcloud_api_key: "{{ lookup('ansible.builtin.env', 'ibmcloud_api_key') }}"
    pi_networks: "{{ lookup('ansible.builtin.env', 'pi_networks') }}"
    pi_ssh_public_key_name: "{{ lookup('ansible.builtin.env', 'pi_ssh_public_key_name') }}"
    pi_existing_workspace_guid: "{{ lookup('ansible.builtin.env', 'pi_existing_workspace_guid') }}"
    cos_service_apikey: "{{ (lookup('ansible.builtin.env', 'ibmcloud_cos_service_credentials') | from_json).apikey }}"
    cos_bucket_name: "{{ (lookup('ansible.builtin.env', 'ibmcloud_cos_configuration') | from_json).cos_bucket_name }}"
  tasks:
    - name: Create a new IBM Cloud CLI session
      ansible.builtin.command:
        cmd: ibmcloud login --apikey {{ ibmcloud_api_key }} -r {{ region }}
      register: login_output
      changed_when: false
      failed_when: login_output.rc != 0
      when:
        - ibmcloud_api_key | default('') | length > 0
        - region | default('') | length > 0
      no_log: false

    - name: Debug login success
      ansible.builtin.debug:
        msg: "Successfully logged in to IBM Cloud region {{ region }}"
      changed_when: false

    - name: Validate the supplied Workspace ID (JSON fetch)
      ansible.builtin.command:
        cmd: ibmcloud pi ws get {{ pi_existing_workspace_guid }} --json
      register: ws_output
      changed_when: false
      failed_when:
        - ws_output.rc != 0
        - ws_output.stdout | from_json is not mapping
      when:
        - pi_existing_workspace_guid | default('') | length > 0
      no_log: false

    - name: Extract Workspace CRN
      ansible.builtin.set_fact:
        workspace_crn: "{{ (ws_output.stdout | from_json).details.crn | default('N/A') }}"
      when:
        - ws_output is defined
        - ws_output.rc == 0
      changed_when: false
      no_log: false

    - name: Debug Workspace ID
      ansible.builtin.debug:
        msg: "The Workspace ID {{ pi_existing_workspace_guid }} is valid. CRN: {{ workspace_crn }}"
      changed_when: false

    - name: Validate the supplied Public SSH key
      ansible.builtin.command:
        cmd: ibmcloud pi ssh get {{ pi_ssh_public_key_name }} --json
      register: ssh_output
      changed_when: false
      failed_when:
        - ssh_output.rc != 0
        - ssh_output.stdout | from_json is not mapping
      when:
        - pi_ssh_public_key_name | default('') | length > 0
      no_log: false

    - name: Debug Public SSH key
      ansible.builtin.debug:
        msg: "The Public SSH key {{ pi_ssh_public_key_name }} is valid."
      changed_when: false

    - name: Connect to the COS Instance using the API key
      ansible.builtin.command:
        cmd: ibmcloud login --apikey {{ cos_service_apikey }} -r {{ region }}
      register: cos_login_output
      changed_when: false
      failed_when:
        - cos_login_output.rc != 0
        - cos_login_output.stdout | from_json is not mapping
      when:
        - cos_service_apikey | default('') | length > 0
      no_log: false

    - name: Check if the supplied COS bucket configuration is correct
      ansible.builtin.command:
        cmd: ibmcloud cos list-buckets --json | jq -r '.Buckets.[].Name' | grep {{ cos_bucket_name }}
      register: cos_bucket_list_check_output
      changed_when: false
      failed_when:
        - cos_bucket_list_check_output.rc != 0
        - cos_bucket_list_check_output.stdout | from_json is not mapping
      when:
        - cos_service_apikey | default('') | length > 0
        - cos_bucket_name | default('') | length > 0
      no_log: false

    - name: All IBM Cloud pre-validations passed
      ansible.builtin.debug:
        msg: "IBM Cloud API, workspace, SSH key, COS Connetivity and Bucket name validations completed successfully."
      when:
        - login_output.rc == 0
        - ws_output.rc == 0
        - ssh_output.rc == 0
        - cos_login_output.rc == 0
        - cos_bucket_list_check_output.rc == 0
      changed_when: false
